### ISSUE TITLE
Hardcoded Discord bot API token

### ISSUE THREAD

**Issue by jezeke** [hvislyset/cits-discord-bot#1]
https://github.com/hvislyset/cits-discord-bot/blob/1b83fc54fc2fb6265caf0741d8fad2c684b4dc4d/config.json#L2

Might not want to include that. Reflects poorly on the quality of UWA's education.
**Curtin represent.**

**Comment by hvislyset** [comment]
Whoops. 😎

**Comment by Accurate0** [comment]
UWA *sighs*
